import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ChevronRight, ChevronLeft, Moon, Sun, Coffee } from "lucide-react";
import { computeTargets, generateWorkoutPlans, generateMealPlans, generateShoppingList, WEEKDAYS, WEEKDAY_LABELS } from "@/lib/fitnessUtils";
import { cn } from "@/lib/utils";

const GOALS = [{value:"lose",label:"Lose Fat",desc:"Calorie deficit, high protein"},{value:"maintain",label:"Maintain",desc:"Recomp & stay strong"},{value:"gain",label:"Build Muscle",desc:"Slight surplus, lift heavy"}];
const ACTIVITY = [{value:"sedentary",label:"Sedentary"},{value:"light",label:"Lightly Active"},{value:"moderate",label:"Moderately Active"},{value:"active",label:"Very Active"}];
const SHIFTS = [{value:"fixed_day",label:"Fixed Day",icon:Sun},{value:"fixed_night",label:"Fixed Night",icon:Moon},{value:"rotating",label:"Rotating",icon:Coffee}];

export default function Onboarding(){
 const navigate=useNavigate(); const [step,setStep]=useState(0); const [saving,setSaving]=useState(false);
 const [form,setForm]=useState({full_name:"",age:"",sex:"male",height_cm:"",weight_kg:"",goal:"lose",activity_level:"moderate",shift_pattern:"fixed_day",work_days:["mon","tue","wed","thu","fri"]});
 const set=(k,v)=>setForm(f=>({...f,[k]:v})); const toggleDay=d=>setForm(f=>({...f,work_days:f.work_days.includes(d)?f.work_days.filter(x=>x!==d):[...f.work_days,d]}));
 const steps=["You","Body","Goal","Shift","Review"];
 const canNext=(()=>{if(step===0)return form.full_name&&form.age;if(step===1)return form.height_cm&&form.weight_kg;if(step===3)return form.work_days.length>0;return true;})();
 const finish=async()=>{setSaving(true);try{const profileData={full_name:form.full_name,age:Number(form.age),sex:form.sex,height_cm:Number(form.height_cm),weight_kg:Number(form.weight_kg),goal:form.goal,activity_level:form.activity_level,shift_pattern:form.shift_pattern,work_days:form.work_days,onboarding_complete:true,...computeTargets({...form,age:Number(form.age),height_cm:Number(form.height_cm),weight_kg:Number(form.weight_kg)})};await base44.entities.UserProfile.create(profileData);await base44.entities.WorkoutPlan.bulkCreate(generateWorkoutPlans(profileData));const meals=generateMealPlans(profileData,profileData);await base44.entities.MealPlan.bulkCreate(meals);await base44.entities.ShoppingListItem.bulkCreate(generateShoppingList(meals));const today=new Date().toISOString().slice(0,10);await base44.entities.WaterLog.create({date:today,amount_ml:0});await base44.entities.StepLog.create({date:today,steps:0});await base44.entities.BodyMetric.create({date:today,weight_kg:Number(form.weight_kg)});navigate("/")}finally{setSaving(false)}};
 return <div className="min-h-screen bg-background px-5 pt-8"><div className="mx-auto max-w-md"><div className="mb-8 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-primary-foreground font-bold">S</div><span className="text-lg font-semibold tracking-tight">ShiftFit</span></div><div className="mb-8 flex items-center gap-1.5">{steps.map((s,i)=><div key={s} className={cn("h-1.5 flex-1 rounded-full transition-colors",i<=step?"bg-primary":"bg-secondary")}/>)}</div>
 {step===0&&<Section title="Let's build your ShiftFit plan" subtitle="Start with the basics."><Field label="Name" value={form.full_name} onChange={v=>set("full_name",v)} placeholder="Your name"/><Field label="Age" value={form.age} onChange={v=>set("age",v)} type="number" placeholder="Age"/><div><Label>Sex</Label><div className="mt-2 grid grid-cols-3 gap-2">{["male","female","other"].map(v=><Chip key={v} active={form.sex===v} onClick={()=>set("sex",v)}>{v[0].toUpperCase()+v.slice(1)}</Chip>)}</div></div></Section>}
 {step===1&&<Section title="Your body" subtitle="We'll use this to calculate your targets."><Field label="Height (cm)" value={form.height_cm} onChange={v=>set("height_cm",v)} type="number" placeholder="e.g. 173"/><Field label="Weight (kg)" value={form.weight_kg} onChange={v=>set("weight_kg",v)} type="number" placeholder="e.g. 84"/></Section>}
 {step===2&&<Section title="What's your goal?" subtitle="Your calories, macros and training adapt to this."><div className="space-y-2">{GOALS.map(g=><button key={g.value} onClick={()=>set("goal",g.value)} className={cn("w-full rounded-2xl border p-4 text-left",form.goal===g.value?"border-primary bg-primary/10":"border-border bg-card")}><div className="font-semibold">{g.label}</div><div className="text-xs text-muted-foreground">{g.desc}</div></button>)}</div><div className="mt-5"><Label>Activity level</Label><div className="mt-2 grid grid-cols-2 gap-2">{ACTIVITY.map(a=><Chip key={a.value} active={form.activity_level===a.value} onClick={()=>set("activity_level",a.value)}>{a.label}</Chip>)}</div></div></Section>}
 {step===3&&<Section title="Your shifts" subtitle="ShiftFit changes your plan around work and recovery."><div className="space-y-2">{SHIFTS.map(s=>{const Icon=s.icon;return <button key={s.value} onClick={()=>set("shift_pattern",s.value)} className={cn("flex w-full items-center gap-3 rounded-2xl border p-4 text-left",form.shift_pattern===s.value?"border-primary bg-primary/10":"border-border bg-card")}><Icon className="h-5 w-5 text-primary"/><span className="font-semibold">{s.label}</span></button>})}</div><div className="mt-5"><Label>Work days</Label><div className="mt-2 grid grid-cols-7 gap-1.5">{WEEKDAYS.map((d,i)=><button key={d} onClick={()=>toggleDay(d)} className={cn("rounded-xl py-2 text-xs font-semibold",form.work_days.includes(d)?"bg-primary text-primary-foreground":"bg-secondary text-muted-foreground")}>{WEEKDAY_LABELS[i][0]}</button>)}</div></div></Section>}
 {step===4&&<Section title="You're ready" subtitle="Review your setup before we build your 7-day plan."><div className="space-y-2 rounded-2xl border border-border bg-card p-4 text-sm"><Row label="Name" value={form.full_name}/><Row label="Body" value={`${form.height_cm} cm · ${form.weight_kg} kg`}/><Row label="Goal" value={GOALS.find(x=>x.value===form.goal)?.label}/><Row label="Activity" value={ACTIVITY.find(x=>x.value===form.activity_level)?.label}/><Row label="Shift" value={SHIFTS.find(x=>x.value===form.shift_pattern)?.label}/><Row label="Work days" value={form.work_days.map(d=>WEEKDAY_LABELS[WEEKDAYS.indexOf(d)]).join(", ")}/></div></Section>}
 <div className="mt-8 flex items-center gap-3">{step>0&&<Button variant="outline" size="icon" onClick={()=>setStep(s=>s-1)} disabled={saving}><ChevronLeft className="h-4 w-4"/></Button>}{step<4?<Button className="flex-1" disabled={!canNext} onClick={()=>setStep(s=>s+1)}>Continue <ChevronRight className="ml-1 h-4 w-4"/></Button>:<Button className="flex-1" disabled={saving} onClick={finish}>{saving?"Building your plan…":"Start ShiftFit"}</Button>}</div></div></div>;
}
function Section({title,subtitle,children}){return <section><h1 className="text-2xl font-bold tracking-tight">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p><div className="mt-6 space-y-4">{children}</div></section>}
function Field({label,value,onChange,type="text",placeholder}){return <div className="space-y-2"><Label>{label}</Label><Input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></div>}
function Chip({active,onClick,children}){return <button type="button" onClick={onClick} className={cn("rounded-xl border px-3 py-2 text-sm",active?"border-primary bg-primary/10 text-primary":"border-border bg-secondary text-muted-foreground")}>{children}</button>}
function Row({label,value}){return <div className="flex justify-between gap-4 border-b border-border py-2 last:border-0"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value}</span></div>}
